In [1]:
import requests

In [2]:
from bs4 import BeautifulSoup

In [3]:
import numpy as np

In [90]:
url="https://www.eazydiner.com/restaurants?date=2026-03-02&meal_period=dinner&location=ahmedabad"
headers={"user-agent":
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36"}

In [91]:
res=requests.get(url,headers=headers)
res

In [92]:
soup=BeautifulSoup(res.text)
soup.text

"The 20 Best Restaurants in AhmedabadMar 2026 | EazyDinerLoginOpen AppYour LocationAhmedabadSearch restaurants, locations or cuisinesBe Prime!Contact UsLoginHome /Ahmedabad / Top Restaurants in AhmedabadAhmedabad Restaurants0FiltersSort byPrimeBuffetPocket friendlyNorth IndianMulticuisine%Flat 30% + 25% with Bank OffersEatOutBella AromaCrowne Plaza, AhmedabadCafe₹700 for two4.6%Flat 35% + 25% with Bank OffersEatOutThe Chocolate RoomPrahlad Nagar, West Ahmedabad\xa0 | View All(22) OutletsBakery₹500 for two5.0%Flat 20% + 25% with Bank OffersEssenceCrowne Plaza, AhmedabadIndian, North Indian₹2000 for two4.5Ad%Flat 10% + 25% with Bank OffersSphere LoungeHotel Ramada, AhmedabadContinental, Indian₹900 for two4.2%Flat 25% + 25% with Bank OffersEatOutLa Milano PizzeriaPrahlad Nagar, West Ahmedabad\xa0 | View All(2) OutletsPizza₹500 for two2.5%Flat 10% + 25% with Bank OffersThe Shaka CafePrahlad Nagar, West AhmedabadMulticuisine₹1000 for two3.9AdAdAd%Flat 10% + 25% with Bank OffersSundewHotel Ramada, AhmedabadMulticuisine₹1400 for two4.4%Flat 50% + 25% with Bank OffersEatOutAmritsar HaveliPrahlad Nagar, West Ahmedabad\xa0 | View All(2) OutletsMulticuisine₹1100 for two3.5%Flat 10% + 25% with Bank OffersHocco KitchenPrahlad Nagar, West Ahmedabad\xa0 | View All(9) OutletsNorth Indian₹1000 for two5.0« Previous12345678...46Next »Popular Cuisines Near MeNorth Indian Restaurants Near MeChinese Restaurants Near MeEuropean Restaurants Near MeItalian Restaurants Near MePan Asian Restaurants Near MeJapanese Restaurants Near MeMediterranean Restaurants Near MeCasual Eclectic Restaurants Near MeSouth Indian Restaurants Near MePopular Restaurants Near MeSakura The Metropolitan Hotel & Spa, New DelhiChutney, Bar + Tandoor The Metropolitan Hotel & Spa, New DelhiZing The Metropolitan Hotel & Spa, New DelhiBarista CoffeeShivaji Stadium Metro Station, Connaught Place (CP), Central DelhiBiryani BluesRajiv Chowk, Delhi NCRBikanervalaConnaught Place (CP), Central Delhi MIST, THE Park New DelhiThe Park, New DelhiDesi VillagioConnaught Place (CP), Central DelhiFifty9 Radisson Blu Marina, New DelhiHard Rock CafeConnaught Place (CP), Central DelhiEau De MonsoonLe Meridien, New DelhiXero CourtyardJanpath, Connaught Place (CP), Central DelhiTop Chains in delhi-ncrBarbeque Nation25 OutletsCafe Delhi Heights30 OutletsChili's8 OutletsPunjab Grill23 OutletsSocial 15 OutletsGola Sizzlers23 OutletsYouMee12 OutletsKarigari By Chef Harpal Singh Sokhi8 OutletseazydinerAbout UsFood trends (Blog)Partner offersDownload AppContact UsCareer discoverTable bookingFast food near mePrepaid deals near meRestaurants Near Me for youPrime SubscriptionPayEazyRefer & EarnTerms & ConditionsPrivacy Policy for restaurantsList your RestaurantLivetable - Restaurants SaaS BOOK BEST RESTAURANTS IN\xa0Delhi NCR |\xa0Mumbai |\xa0Bengaluru |\xa0Chennai |\xa0Pune |\xa0Kolkata |\xa0Dubai |\xa0Goa |\xa0Ahmedabad |\xa0Jaipur |\xa0Agra |\xa0Hyderabad |\xa0Lucknow |\xa0Kochi |\xa0Coimbatore |\xa0Ranchi |\xa0Visakhapatnam |\xa0Patna |\xa0Amritsar |\xa0Bhubaneswar |\xa0Indore |\xa0Ludhiana |\xa0Mysuru |\xa0Vadodara |\xa0Thiruvananthapuram |\xa0Nagpur |\xa0Udaipur |\xa0Madurai |\xa0Abu Dhabi |\xa0Chandigarh Tricity |\xa0Mangalore Tricity |\xa0All CitiesExplore best restaurants nearby Ahmedabad!© EazyDiner Private Limited.786 100 4444Connect with us:"

In [93]:
r_name=soup.find_all("div",attrs={"class":"relative bold ellipsis listing_res_name__uVIN8"})
for n in r_name:
    print(n.text)

Bella Aroma
The Chocolate Room
Essence
Sphere Lounge
La Milano Pizzeria
The Shaka Cafe
Sundew
Amritsar Haveli
Hocco Kitchen

In [94]:
r_location=soup.find_all("div",attrs={"class":"flex align-v-center gap_5 padding relative"})
for l in r_location:
    print(l.text)

Crowne Plaza, Ahmedabad
Prahlad Nagar, West Ahmedabad  | View All(22) Outlets
Crowne Plaza, Ahmedabad
Hotel Ramada, Ahmedabad
Prahlad Nagar, West Ahmedabad  | View All(2) Outlets
Prahlad Nagar, West Ahmedabad
Hotel Ramada, Ahmedabad
Prahlad Nagar, West Ahmedabad  | View All(2) Outlets
Prahlad Nagar, West Ahmedabad  | View All(9) Outlets

In [95]:
r_details=soup.find_all("div",attrs={"class":"flex align-v-center gap_5 relative"})
for p in r_details:
    print(p.text)

Cafe₹700 for two
Bakery₹500 for two
Indian, North Indian₹2000 for two
Continental, Indian₹900 for two
Pizza₹500 for two
Multicuisine₹1000 for two
Multicuisine₹1400 for two
Multicuisine₹1100 for two
North Indian₹1000 for two

In [ ]:
#https://www.eazydiner.com/restaurants?city=pune&location=pune&cuisines%5B%5D=italian&cuisines%5B%5D=italian&page=2

In [8]:
import numpy as np

In [9]:
r_servings=soup.find_all("div",attrs={"class":"relative font-16 grey ellipsis listing_lh_18__xp_N9"})

In [96]:
len(restaurant_name),len(restaurant_location),len(res_details),len(res_offers)

(1242, 1242, 1242, 1242)

In [15]:
restaurant_name=[]
restaurant_location=[]
res_details=[]
res_offers=[]

for i in range(1,5):
    url=f"https://www.eazydiner.com/restaurants?date=2026-03-02&meal_period=dinner&location=ahmedabad&page={i}"
    headers={"user-agent":
             "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36"}

    res=requests.get(url,headers=headers)
    soup=BeautifulSoup(res.text)
    containers=soup.find_all("div",attrs={"class":"flex align-v-start flex-between padding-t-15 padding-b-15 margin-t-12 relative full-width"})
    for c in containers:
        r_name=c.find("div",attrs={"class":"relative bold ellipsis listing_res_name__uVIN8"})
        if r_name is None:
            restaurant_name.append(np.nan)
        else:
            restaurant_name.append(r_name.text)

        r_location=c.find("div",attrs={"class":"flex align-v-center gap_5 padding relative"})
        if r_location is None:
            restaurant_location.append(np.nan)
        else:
            restaurant_location.append(r_location.text)

        r_details=c.find("div",attrs={"class":"flex align-v-center gap_5 relative"})
        if r_details is None:
            res_details.append(np.nan)
        else:
            res_details.append(r_details.text)

        offers=soup.find("div",attrs={"class":"relative font-16 bold white nowrap ellipsis"})
        if offers is None:
            res_offers.append(np.nan)
        else:
            res_offers.append(offers.text)

In [16]:
len(restaurant_name),len(restaurant_location),len(res_details),len(res_offers)

(0, 0, 0, 0)

In [17]:
#l=["pune","mumbai","udaipur","jaipur","goa","hyderabad","delhi-ncr","bengaluru","chandigarh-tricity"]
for i in range(1,5):
    url_1=f"https://www.eazydiner.com/restaurants?date=2026-03-02&meal_period=dinner&location=mangalore-tricity&page={i}"
    headers={"user-agent":
                 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36"}

    res=requests.get(url_1,headers=headers)
    soup=BeautifulSoup(res.text)
    containers=soup.find_all("div",attrs={"class":"flex align-v-start flex-between padding-t-15 padding-b-15 margin-t-12 relative full-width"})
    for c in containers:
        r_name=c.find("div",attrs={"class":"relative bold ellipsis listing_res_name__uVIN8"})
        if r_name is None:
            restaurant_name.append(np.nan)
        else:
            restaurant_name.append(r_name.text)

        r_location=c.find("div",attrs={"class":"flex align-v-center gap_5 padding relative"})
        if r_location is None:
            restaurant_location.append(np.nan)
        else:
            restaurant_location.append(r_location.text)

        r_details=c.find("div",attrs={"class":"flex align-v-center gap_5 relative"})
        if r_details is None:
            res_details.append(np.nan)
        else:
            res_details.append(r_details.text)

        offers=soup.find("div",attrs={"class":"relative font-16 bold white nowrap ellipsis"})
        if offers is None:
            res_offer.append(np.nan)
        else:
            res_offers.append(offers.text)

In [18]:
len(restaurant_name),len(restaurant_location),len(res_details),len(res_offers)

(0, 0, 0, 0)

In [19]:
restaurant_location

[]

In [4]:
import pandas as pd

In [165]:
df=pd.DataFrame({"res_name":restaurant_name,"res_location":restaurant_location,"res_details":res_details,"res_offers":res_offers})

In [166]:
df.tail(50)

,res_name,res_location,res_details,res_offers
3841,Donne Biryani Empire,Udupi,Biryani₹650 for two,25% Off :Payeazy
3842,Karthik Fine Dine,"Kidiyoor, Mangalore Tricity",Multicuisine₹1000 for two,25% Off :Payeazy
3843,Chavadi,"Ambalpadi, Udupi",Multicuisine₹450 for two,25% Off :Payeazy
3844,The Black Cafe,"Deralakatte, Mangalore","Cafe, Beverages₹500 for two",25% Off :Payeazy
3845,Veg Treat Hotel,"Nadsal, Udupi",Indian₹500 for two,25% Off :Payeazy
3846,Sahana Fish N Curry Sea Food Restaurant,"Kundapura, Mangalore Tricity",Seafood₹400 for two,25% Off :Payeazy
3847,Hotel Narayan's Seashell,"Chitpady, Mangalore Tricity",Multicuisine₹800 for two,25% Off :Payeazy
3848,Freddy's Restro Cafe,"Fortune Plaza Hotel, Udupi",Multicuisine₹1200 for two,25% Off :Payeazy
3849,Coastal Family Restaurant,"Kaup, Udupi",Multicuisine₹500 for two,25% Off :Payeazy
3850,Kediyoor's Zone,"Kediyoor Hotels pvt ltd, Udupi","Cocktail Menu, Multicuisine₹800 for two",25% Off :Payeazy
3851,Madhuvan Mandara Multi Cuisine Restaurant,"Hotel Madhuvan Serai, Manipal",Multicuisine₹850 for two,25% Off :Payeazy
3852,Wine & Dine Family Restaurant,"SH 101, Mangalore",Indian₹700 for two,25% Off :Payeazy
3853,Rockside Resto Bar,"Karkala, Udupi",Multicuisine₹800 for two,25% Off :Payeazy
3854,Time Square Coral Multicuisine,"Kunjibettu, Udupi",Multicuisine₹1000 for two,25% Off :Payeazy
3855,Charcoal BBQ Restaurant,"Ananth Nagar, Manipal",Multicuisine₹300 for two,25% Off :Payeazy
3856,Vivaan Restaurant,"Brahmagiri, Udupi",Indian₹600 for two,25% Off :Payeazy
3857,Garden Restaurant,"Mulki, Mangalore",Fast Food₹700 for two,25% Off :Payeazy
3858,Golden Scoop Ice Cream Parlour,"Bajpe, Mangalore",Cafe₹400 for two,25% Off :Payeazy
3859,The Postcard On The Arabian Sea,"Trasi, Mangalore Tricity",Multicuisine₹2000 for two,25% Off :Payeazy
3860,Malpe lunch home,"Malpe, Udupi",Multicuisine₹700 for two,25% Off :Payeazy
3861,Chavadi By Sadanand,"Hotel Sadanand, Mangalore",Multicuisine₹800 for two,25% Off :Payeazy
3862,Sharief Bhai Biryani,"Ullal, Mangalore",Biryani₹1000 for two,25% Off :Payeazy
3863,Manpasand By Shambhavi,"Brahmagiri, Udupi","Multicuisine, Cocktail Menu₹1000 for two",25% Off :Payeazy
3864,Madhuvan Veg,"Hotel Madhuvan Serai, Manipal",Multicuisine₹500 for two,25% Off :Payeazy
3865,Hitchki Lounge By Shambavi,"Brahmagiri, Udupi","Finger Food, Cocktail Menu₹1000 for two",25% Off :Payeazy
3866,The Waffle Street,"Vidyaratna Nagar, Manipal",Desserts₹400 for two,25% Off :Payeazy
3867,Breeze Rooftop,"Ullal, Mangalore",Multicuisine₹1000 for two,25% Off :Payeazy
3868,Kutumbh Fine Dine Family Restaurant,"Ullal, Mangalore",Multicuisine₹800 for two,25% Off :Payeazy
3869,Hotel Pancharathna International,"Mudbidri, Mangalore Tricity",Multicuisine₹1000 for two,25% Off :Payeazy
3870,Zero Degrees Family Lounge & Bar,Manipal,"Finger Food, Cocktail Menu₹1000 for two",25% Off :Payeazy
3871,Hotel Sanman,"Padebettu, Mangalore Tricity",Indian₹800 for two,25% Off :Payeazy
3872,Chicken Frito,Hotel Central Park,Fast Food₹700 for two,25% Off :Payeazy
3873,Koyla restaurant,"Kaikamba, Mangalore | View All(2) Outlets",Multicuisine₹800 for two,25% Off :Payeazy
3874,Nash Flavour House,Udupi,Cafe₹1000 for two,25% Off :Payeazy
3875,Genie Shai,"Vidyaratna Nagar, Manipal",Cafe₹400 for two,25% Off :Payeazy
3876,Friendly Fried Chicken Aka Friendly Darbar,"Manipal Inn, Udupi",Multicuisine₹600 for two,25% Off :Payeazy
3877,Scoops N Smiles,"Surathkal , Mangalore",Multicuisine₹400 for two,25% Off :Payeazy
3878,Lighthouse Seafood Restaurant & Bar,"Padu, Udupi",Indian₹900 for two,25% Off :Payeazy
3879,Madhuvan Non Alcoholic Fine Dine,"Padu, Udupi",Indian₹800 for two,25% Off :Payeazy
3880,Kenz Al Arab Resto Cafe,"Vidyaratna Nagar, Manipal",Multicuisine₹700 for two,25% Off :Payeazy
3881,V6 The Lounge,"Ullal, Mangalore","Cocktail Menu, Multicuisine₹800 for two",25% Off :Payeazy
3882,Fortune Rasa Cafe,"Fortune Plaza Hotel, Udupi",Multicuisine₹650 for two,25% Off :Payeazy
3883,Anup Lunch Home,"Kaup, Udupi",Indian₹800 for two,25% Off :Payeazy
3884,Hotel Ratna Palace,Karavali Bypass,Multicuisine₹500 for two,25% Off :Payeazy
3885,Spicy Kitchen,"Surathkal , Mangalore | View All(2) Outlets",Multicuisine₹600 for two,25% Off :Payeazy
3886,Juice It Up Resto Cafe,"Deralakatte, Mangalore",Fast Food₹650 for two,25% Off :Payeazy
3887,Bhramari Pure Veg,"Padu, Udupi",Indian₹500 for two,25% Off :Payeazy
3888,The Udupi Express,"Padubidri, Udupi",South Indian₹500 for two,25% Off :Payeazy
3889,Grill House,"Moodabidri, Mangalore",Multicuisine₹650 for two,25% Off :Payeazy
3890,Sarova Family Bar & Restaurant,"Padubidri, Udupi",Multicuisine₹800 for two,25% Off :Payeazy

In [167]:
df.to_csv("eazy_dinner3.csv")

In [5]:
df_1=pd.read_csv("eazy_dinner3.csv")

In [7]:
df_1

,Unnamed: 0,res_name,res_location,res_details,res_offers
0,0,Bella Aroma,"Crowne Plaza, Ahmedabad",Cafe₹700 for two,Flat 30% + 25% with Bank Offers
1,1,The Chocolate Room,"Prahlad Nagar, West Ahmedabad | View All(22) ...",Bakery₹500 for two,Flat 30% + 25% with Bank Offers
2,2,Essence,"Crowne Plaza, Ahmedabad","Indian, North Indian₹2000 for two",Flat 30% + 25% with Bank Offers
3,3,Sphere Lounge,"Hotel Ramada, Ahmedabad","Continental, Indian₹900 for two",Flat 30% + 25% with Bank Offers
4,4,La Milano Pizzeria,"Prahlad Nagar, West Ahmedabad | View All(2) O...",Pizza₹500 for two,Flat 30% + 25% with Bank Offers
...,...,...,...,...,...
3886,3886,Juice It Up Resto Cafe,"Deralakatte, Mangalore",Fast Food₹650 for two,25% Off :Payeazy
3887,3887,Bhramari Pure Veg,"Padu, Udupi",Indian₹500 for two,25% Off :Payeazy
3888,3888,The Udupi Express,"Padubidri, Udupi",South Indian₹500 for two,25% Off :Payeazy
3889,3889,Grill House,"Moodabidri, Mangalore",Multicuisine₹650 for two,25% Off :Payeazy
3890,3890,Sarova Family Bar & Restaurant,"Padubidri, Udupi",Multicuisine₹800 for two,25% Off :Payeazy

In [34]:
df_1["res_location"].head(30).values

array(['Crowne Plaza, Ahmedabad',
       'Prahlad Nagar, West Ahmedabad\xa0 | View All(22) Outlets',
       'Crowne Plaza, Ahmedabad', 'Hotel Ramada, Ahmedabad',
       'Prahlad Nagar, West Ahmedabad\xa0 | View All(2) Outlets',
       'Prahlad Nagar, West Ahmedabad', 'Hotel Ramada, Ahmedabad',
       'Prahlad Nagar, West Ahmedabad\xa0 | View All(2) Outlets',
       'Prahlad Nagar, West Ahmedabad\xa0 | View All(9) Outlets',
       'Prahlad Nagar, West Ahmedabad\xa0 | View All(4) Outlets',
       'Prahlad Nagar, West Ahmedabad\xa0 | View All(4) Outlets',
       'Prahlad Nagar, West Ahmedabad', 'Prahlad Nagar, West Ahmedabad',
       'Satellite, West Ahmedabad',
       'Prahlad Nagar, West Ahmedabad\xa0 | View All(2) Outlets',
       'Prahlad Nagar, West Ahmedabad', 'Prahlad Nagar, West Ahmedabad',
       'Holiday Inn Express Ahmedabad Prahlad Nagar ',
       'Bodakdev, West Ahmedabad', 'Prahlad Nagar, West Ahmedabad',
       'Prahlad Nagar, West Ahmedabad', 'Satellite, West Ahmedabad',
       'Satellite, West Ahmedabad\xa0 | View All(8) Outlets',
       'Makarba, Ahmedabad',
       'Jodhpur Village, Ahmedabad\xa0 | View All(2) Outlets',
       'SOBO Center, Bopal\xa0 | View All(2) Outlets',
       'DoubleTree by Hilton Ahmedabad', 'Bodakdev, West Ahmedabad',
       'Bodakdev, West Ahmedabad',
       'Prahlad Nagar, West Ahmedabad\xa0 | View All(5) Outlets'],
      dtype=object)

In [24]:
import re

In [25]:
regex=r".*?\b(?:Ahmedabad|Pune|Mangalore|Udaipur|jaipur|Goa|Hyderabad|Bengaluru|Chandigarh|Manipal|Mumbai|Mohali|Thiruvananthapuram|Manglore|Udupi)\b"
df_1["Location"]=df_1["res_location"].apply(lambda x : re.findall(regex, x)[0] if re.findall(regex, x) else None)

In [31]:
df_1.head(10)

,Unnamed: 0,res_name,res_location,res_details,res_offers,Location
0,0,Bella Aroma,"Crowne Plaza, Ahmedabad",Cafe₹700 for two,Flat 30% + 25% with Bank Offers,"Crowne Plaza, Ahmedabad"
1,1,The Chocolate Room,"Prahlad Nagar, West Ahmedabad | View All(22) ...",Bakery₹500 for two,Flat 30% + 25% with Bank Offers,"Prahlad Nagar, West Ahmedabad"
2,2,Essence,"Crowne Plaza, Ahmedabad","Indian, North Indian₹2000 for two",Flat 30% + 25% with Bank Offers,"Crowne Plaza, Ahmedabad"
3,3,Sphere Lounge,"Hotel Ramada, Ahmedabad","Continental, Indian₹900 for two",Flat 30% + 25% with Bank Offers,"Hotel Ramada, Ahmedabad"
4,4,La Milano Pizzeria,"Prahlad Nagar, West Ahmedabad | View All(2) O...",Pizza₹500 for two,Flat 30% + 25% with Bank Offers,"Prahlad Nagar, West Ahmedabad"
5,5,The Shaka Cafe,"Prahlad Nagar, West Ahmedabad",Multicuisine₹1000 for two,Flat 30% + 25% with Bank Offers,"Prahlad Nagar, West Ahmedabad"
6,6,Sundew,"Hotel Ramada, Ahmedabad",Multicuisine₹1400 for two,Flat 30% + 25% with Bank Offers,"Hotel Ramada, Ahmedabad"
7,7,Amritsar Haveli,"Prahlad Nagar, West Ahmedabad | View All(2) O...",Multicuisine₹1100 for two,Flat 30% + 25% with Bank Offers,"Prahlad Nagar, West Ahmedabad"
8,8,Hocco Kitchen,"Prahlad Nagar, West Ahmedabad | View All(9) O...",North Indian₹1000 for two,Flat 30% + 25% with Bank Offers,"Prahlad Nagar, West Ahmedabad"
9,9,Grill Kitchen,"Prahlad Nagar, West Ahmedabad | View All(4) O...",Multicuisine₹1000 for two,Flat 15% + 25% with Bank Offers,"Prahlad Nagar, West Ahmedabad"

In [30]:
df_1["Location"].tail(30).values

array(['Hotel Sadanand, Mangalore', 'Ullal, Mangalore',
       'Brahmagiri, Udupi', 'Hotel Madhuvan Serai, Manipal',
       'Brahmagiri, Udupi', 'Vidyaratna Nagar, Manipal',
       'Ullal, Mangalore', 'Ullal, Mangalore', 'Mudbidri, Mangalore',
       'Manipal', 'Padebettu, Mangalore', None, 'Kaikamba, Mangalore',
       'Udupi', 'Vidyaratna Nagar, Manipal', 'Manipal',
       'Surathkal , Mangalore', 'Padu, Udupi', 'Padu, Udupi',
       'Vidyaratna Nagar, Manipal', 'Ullal, Mangalore',
       ' Fortune Plaza Hotel, Udupi', 'Kaup, Udupi', None,
       'Surathkal , Mangalore', 'Deralakatte, Mangalore', 'Padu, Udupi',
       'Padubidri, Udupi', 'Moodabidri, Mangalore', 'Padubidri, Udupi'],
      dtype=object)

In [35]:
regex=r"\b(Ahmedabad|Pune|Mangalore|Udaipur|jaipur|Goa|Hyderabad|Bengaluru|Chandigarh|Manipal|Mumbai|Mohali|Thiruvananthapuram|Manglore|Udupi)\b"
df_1["res_states"]=df_1["res_location"].apply(lambda x : re.findall(regex, x)[0] if re.findall(regex, x) else None)

In [44]:
df_1.tail(100)

,Unnamed: 0,res_name,res_location,res_details,res_offers,Location,res_states
3791,3791,Hashtag Cafe,"Deralakatte, Mangalore",Cafe₹700 for two,Free Dessert + 25% Off,"Deralakatte, Mangalore",Mangalore
3792,3792,Onyx Air Lounge & Kitchen,"Kodailbail, Mangalore",Multicuisine₹900 for two,Free Dessert + 25% Off,"Kodailbail, Mangalore",Mangalore
3793,3793,Aroma,"Kodailbail, Mangalore",Multicuisine₹1000 for two,Free Dessert + 25% Off,"Kodailbail, Mangalore",Mangalore
3794,3794,The Royal Kitchen,"Kodailbail, Mangalore",North Indian₹600 for two,Free Dessert + 25% Off,"Kodailbail, Mangalore",Mangalore
3795,3795,De-c-Adda,"Kankanady, Mangalore",Multicuisine₹500 for two,Free Dessert + 25% Off,"Kankanady, Mangalore",Mangalore
...,...,...,...,...,...,...,...
3886,3886,Juice It Up Resto Cafe,"Deralakatte, Mangalore",Fast Food₹650 for two,25% Off :Payeazy,"Deralakatte, Mangalore",Mangalore
3887,3887,Bhramari Pure Veg,"Padu, Udupi",Indian₹500 for two,25% Off :Payeazy,"Padu, Udupi",Udupi
3888,3888,The Udupi Express,"Padubidri, Udupi",South Indian₹500 for two,25% Off :Payeazy,"Padubidri, Udupi",Udupi
3889,3889,Grill House,"Moodabidri, Mangalore",Multicuisine₹650 for two,25% Off :Payeazy,"Moodabidri, Mangalore",Mangalore
3890,3890,Sarova Family Bar & Restaurant,"Padubidri, Udupi",Multicuisine₹800 for two,25% Off :Payeazy,"Padubidri, Udupi",Udupi

In [51]:
df_1["res_offers"].tail(10).values

array(['25% Off :Payeazy', '25% Off :Payeazy', '25% Off :Payeazy',
       '25% Off :Payeazy', '25% Off :Payeazy', '25% Off :Payeazy',
       '25% Off :Payeazy', '25% Off :Payeazy', '25% Off :Payeazy',
       '25% Off :Payeazy'], dtype=object)

In [45]:
regex=r"^(.*?)₹"
df_1["res_cuisines"]=df_1["res_details"].apply(lambda x : re.findall(regex, x)[0] if re.findall(regex, x) else None)

In [46]:
df_1

,Unnamed: 0,res_name,res_location,res_details,res_offers,Location,res_states,res_cuisines
0,0,Bella Aroma,"Crowne Plaza, Ahmedabad",Cafe₹700 for two,Flat 30% + 25% with Bank Offers,"Crowne Plaza, Ahmedabad",Ahmedabad,Cafe
1,1,The Chocolate Room,"Prahlad Nagar, West Ahmedabad | View All(22) ...",Bakery₹500 for two,Flat 30% + 25% with Bank Offers,"Prahlad Nagar, West Ahmedabad",Ahmedabad,Bakery
2,2,Essence,"Crowne Plaza, Ahmedabad","Indian, North Indian₹2000 for two",Flat 30% + 25% with Bank Offers,"Crowne Plaza, Ahmedabad",Ahmedabad,"Indian, North Indian"
3,3,Sphere Lounge,"Hotel Ramada, Ahmedabad","Continental, Indian₹900 for two",Flat 30% + 25% with Bank Offers,"Hotel Ramada, Ahmedabad",Ahmedabad,"Continental, Indian"
4,4,La Milano Pizzeria,"Prahlad Nagar, West Ahmedabad | View All(2) O...",Pizza₹500 for two,Flat 30% + 25% with Bank Offers,"Prahlad Nagar, West Ahmedabad",Ahmedabad,Pizza
...,...,...,...,...,...,...,...,...
3886,3886,Juice It Up Resto Cafe,"Deralakatte, Mangalore",Fast Food₹650 for two,25% Off :Payeazy,"Deralakatte, Mangalore",Mangalore,Fast Food
3887,3887,Bhramari Pure Veg,"Padu, Udupi",Indian₹500 for two,25% Off :Payeazy,"Padu, Udupi",Udupi,Indian
3888,3888,The Udupi Express,"Padubidri, Udupi",South Indian₹500 for two,25% Off :Payeazy,"Padubidri, Udupi",Udupi,South Indian
3889,3889,Grill House,"Moodabidri, Mangalore",Multicuisine₹650 for two,25% Off :Payeazy,"Moodabidri, Mangalore",Mangalore,Multicuisine
3890,3890,Sarova Family Bar & Restaurant,"Padubidri, Udupi",Multicuisine₹800 for two,25% Off :Payeazy,"Padubidri, Udupi",Udupi,Multicuisine

In [49]:
regex=r"₹\d+\s*"
df_1["res_prise"]=df_1["res_details"].apply(lambda x : re.findall(regex, x)[0] if re.findall(regex, x) else None)

In [50]:
df_1

,Unnamed: 0,res_name,res_location,res_details,res_offers,Location,res_states,res_cuisines,res_prise
0,0,Bella Aroma,"Crowne Plaza, Ahmedabad",Cafe₹700 for two,Flat 30% + 25% with Bank Offers,"Crowne Plaza, Ahmedabad",Ahmedabad,Cafe,₹700
1,1,The Chocolate Room,"Prahlad Nagar, West Ahmedabad | View All(22) ...",Bakery₹500 for two,Flat 30% + 25% with Bank Offers,"Prahlad Nagar, West Ahmedabad",Ahmedabad,Bakery,₹500
2,2,Essence,"Crowne Plaza, Ahmedabad","Indian, North Indian₹2000 for two",Flat 30% + 25% with Bank Offers,"Crowne Plaza, Ahmedabad",Ahmedabad,"Indian, North Indian",₹2000
3,3,Sphere Lounge,"Hotel Ramada, Ahmedabad","Continental, Indian₹900 for two",Flat 30% + 25% with Bank Offers,"Hotel Ramada, Ahmedabad",Ahmedabad,"Continental, Indian",₹900
4,4,La Milano Pizzeria,"Prahlad Nagar, West Ahmedabad | View All(2) O...",Pizza₹500 for two,Flat 30% + 25% with Bank Offers,"Prahlad Nagar, West Ahmedabad",Ahmedabad,Pizza,₹500
...,...,...,...,...,...,...,...,...,...
3886,3886,Juice It Up Resto Cafe,"Deralakatte, Mangalore",Fast Food₹650 for two,25% Off :Payeazy,"Deralakatte, Mangalore",Mangalore,Fast Food,₹650
3887,3887,Bhramari Pure Veg,"Padu, Udupi",Indian₹500 for two,25% Off :Payeazy,"Padu, Udupi",Udupi,Indian,₹500
3888,3888,The Udupi Express,"Padubidri, Udupi",South Indian₹500 for two,25% Off :Payeazy,"Padubidri, Udupi",Udupi,South Indian,₹500
3889,3889,Grill House,"Moodabidri, Mangalore",Multicuisine₹650 for two,25% Off :Payeazy,"Moodabidri, Mangalore",Mangalore,Multicuisine,₹650
3890,3890,Sarova Family Bar & Restaurant,"Padubidri, Udupi",Multicuisine₹800 for two,25% Off :Payeazy,"Padubidri, Udupi",Udupi,Multicuisine,₹800

In [52]:
df_1.drop(columns=["res_location","res_details"], inplace=True)

In [53]:
df_1

,Unnamed: 0,res_name,res_offers,Location,res_states,res_cuisines,res_prise
0,0,Bella Aroma,Flat 30% + 25% with Bank Offers,"Crowne Plaza, Ahmedabad",Ahmedabad,Cafe,₹700
1,1,The Chocolate Room,Flat 30% + 25% with Bank Offers,"Prahlad Nagar, West Ahmedabad",Ahmedabad,Bakery,₹500
2,2,Essence,Flat 30% + 25% with Bank Offers,"Crowne Plaza, Ahmedabad",Ahmedabad,"Indian, North Indian",₹2000
3,3,Sphere Lounge,Flat 30% + 25% with Bank Offers,"Hotel Ramada, Ahmedabad",Ahmedabad,"Continental, Indian",₹900
4,4,La Milano Pizzeria,Flat 30% + 25% with Bank Offers,"Prahlad Nagar, West Ahmedabad",Ahmedabad,Pizza,₹500
...,...,...,...,...,...,...,...
3886,3886,Juice It Up Resto Cafe,25% Off :Payeazy,"Deralakatte, Mangalore",Mangalore,Fast Food,₹650
3887,3887,Bhramari Pure Veg,25% Off :Payeazy,"Padu, Udupi",Udupi,Indian,₹500
3888,3888,The Udupi Express,25% Off :Payeazy,"Padubidri, Udupi",Udupi,South Indian,₹500
3889,3889,Grill House,25% Off :Payeazy,"Moodabidri, Mangalore",Mangalore,Multicuisine,₹650
3890,3890,Sarova Family Bar & Restaurant,25% Off :Payeazy,"Padubidri, Udupi",Udupi,Multicuisine,₹800

In [57]:
df_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3891 entries, 0 to 3890
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    3891 non-null   int64
 1   res_name      3891 non-null   object
 2   res_offers    3891 non-null   object
 3   Location      3058 non-null   object
 4   res_states    3058 non-null   object
 5   res_cuisines  3891 non-null   object
 6   res_prise     3891 non-null   object
dtypes: int64(1), object(6)
memory usage: 212.9+ KB

In [61]:
df_1.to_csv("eazy_dinner_clean_Data.csv",index=False)